# Generated by Django 5.0.4 on 2024-04-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_slug_to_post'),
    ]

    operations = [
    ]
